// ===================================
// INGREDIENTS DATABASE WITH ICONS
// ===================================

export const INGREDIENTS_DATABASE = {
  // Proteine & Fleisch
  proteins: [
    { id: 'chicken', name: 'Hähnchen', icon: '🍗', category: 'Fleisch' },
    { id: 'chicken_breast', name: 'Hähnchenbrust', icon: '🍗', category: 'Fleisch' },
    { id: 'beef', name: 'Rindfleisch', icon: '🥩', category: 'Fleisch' },
    { id: 'ground_beef', name: 'Hackfleisch', icon: '🥩', category: 'Fleisch' },
    { id: 'steak', name: 'Steak', icon: '🥩', category: 'Fleisch' },
    { id: 'pork', name: 'Schweinefleisch', icon: '🥓', category: 'Fleisch' },
    { id: 'bacon', name: 'Speck', icon: '🥓', category: 'Fleisch' },
    { id: 'ham', name: 'Schinken', icon: '🥓', category: 'Fleisch' },
    { id: 'sausage', name: 'Wurst', icon: '🌭', category: 'Fleisch' },
    { id: 'turkey', name: 'Pute', icon: '🦃', category: 'Fleisch' },
    { id: 'lamb', name: 'Lamm', icon: '🐑', category: 'Fleisch' },
    { id: 'duck', name: 'Ente', icon: '🦆', category: 'Fleisch' },
    { id: 'salmon', name: 'Lachs', icon: '🐟', category: 'Fisch' },
    { id: 'tuna', name: 'Thunfisch', icon: '🐠', category: 'Fisch' },
    { id: 'shrimp', name: 'Garnelen', icon: '🦐', category: 'Fisch' },
    { id: 'cod', name: 'Kabeljau', icon: '🐟', category: 'Fisch' },
    { id: 'trout', name: 'Forelle', icon: '🐟', category: 'Fisch' },
    { id: 'mussels', name: 'Muscheln', icon: '🧪', category: 'Fisch' },
    { id: 'eggs', name: 'Eier', icon: '🥚', category: 'Protein' },
    { id: 'tofu', name: 'Tofu', icon: '🧈', category: 'Vegetarisch' },
    { id: 'tempeh', name: 'Tempeh', icon: '🟫', category: 'Vegetarisch' },
    { id: 'lentils', name: 'Linsen', icon: '🫘', category: 'Hülsenfrucht' },
    { id: 'red_lentils', name: 'Rote Linsen', icon: '🫘', category: 'Hülsenfrucht' },
    { id: 'chickpeas', name: 'Kichererbsen', icon: '🟤', category: 'Hülsenfrucht' },
    { id: 'beans', name: 'Bohnen', icon: '🫘', category: 'Hülsenfrucht' },
    { id: 'kidney_beans', name: 'Kidneybohnen', icon: '🫘', category: 'Hülsenfrucht' },
    { id: 'white_beans', name: 'Weiße Bohnen', icon: '🫘', category: 'Hülsenfrucht' },
  ],

  // Gemüse
  vegetables: [
    { id: 'tomato', name: 'Tomate', icon: '🍅', category: 'Gemüse' },
    { id: 'cherry_tomato', name: 'Kirschtomaten', icon: '🍅', category: 'Gemüse' },
    { id: 'onion', name: 'Zwiebel', icon: '🧅', category: 'Gemüse' },
    { id: 'red_onion', name: 'Rote Zwiebel', icon: '🧅', category: 'Gemüse' },
    { id: 'shallot', name: 'Schalotte', icon: '🧅', category: 'Gemüse' },
    { id: 'spring_onion', name: 'Frühlingszwiebel', icon: '🧅', category: 'Gemüse' },
    { id: 'leek', name: 'Lauch', icon: '🥬', category: 'Gemüse' },
    { id: 'garlic', name: 'Knoblauch', icon: '🧄', category: 'Gemüse' },
    { id: 'carrot', name: 'Karotte', icon: '🥕', category: 'Gemüse' },
    { id: 'potato', name: 'Kartoffel', icon: '🥔', category: 'Gemüse' },
    { id: 'sweet_potato', name: 'Süßkartoffel', icon: '🍠', category: 'Gemüse' },
    { id: 'bell_pepper', name: 'Paprika', icon: '🫑', category: 'Gemüse' },
    { id: 'cucumber', name: 'Gurke', icon: '🥒', category: 'Gemüse' },
    { id: 'pickle', name: 'Gewürzgurke', icon: '🥒', category: 'Gemüse' },
    { id: 'lettuce', name: 'Kopfsalat', icon: '🥬', category: 'Gemüse' },
    { id: 'arugula', name: 'Rucola', icon: '🥬', category: 'Gemüse' },
    { id: 'spinach', name: 'Spinat', icon: '🥬', category: 'Gemüse' },
    { id: 'kale', name: 'Grünkohl', icon: '🥬', category: 'Gemüse' },
    { id: 'broccoli', name: 'Brokkoli', icon: '🥦', category: 'Gemüse' },
    { id: 'cauliflower', name: 'Blumenkohl', icon: '🥦', category: 'Gemüse' },
    { id: 'brussels_sprouts', name: 'Rosenkohl', icon: '🥬', category: 'Gemüse' },
    { id: 'mushroom', name: 'Champignon', icon: '🍄', category: 'Gemüse' },
    { id: 'corn', name: 'Mais', icon: '🌽', category: 'Gemüse' },
    { id: 'peas', name: 'Erbsen', icon: '🟢', category: 'Gemüse' },
    { id: 'green_beans', name: 'Grüne Bohnen', icon: '🥒', category: 'Gemüse' },
    { id: 'zucchini', name: 'Zucchini', icon: '🥒', category: 'Gemüse' },
    { id: 'eggplant', name: 'Aubergine', icon: '🍆', category: 'Gemüse' },
    { id: 'avocado', name: 'Avocado', icon: '🥑', category: 'Gemüse' },
    { id: 'celery', name: 'Sellerie', icon: '🥬', category: 'Gemüse' },
    { id: 'cabbage', name: 'Weißkohl', icon: '🥬', category: 'Gemüse' },
    { id: 'red_cabbage', name: 'Rotkohl', icon: '🥬', category: 'Gemüse' },
    { id: 'asparagus', name: 'Spargel', icon: '🥬', category: 'Gemüse' },
    { id: 'fennel', name: 'Fenchel', icon: '🥬', category: 'Gemüse' },
    { id: 'radish', name: 'Radieschen', icon: '🔴', category: 'Gemüse' },
    { id: 'beetroot', name: 'Rote Bete', icon: '🔴', category: 'Gemüse' },
    { id: 'pumpkin', name: 'Kürbis', icon: '🎃', category: 'Gemüse' },
    { id: 'artichoke', name: 'Artischocke', icon: '🥬', category: 'Gemüse' },
  ],

  // Obst
  fruits: [
    { id: 'apple', name: 'Apfel', icon: '🍎', category: 'Obst' },
    { id: 'banana', name: 'Banane', icon: '🍌', category: 'Obst' },
    { id: 'orange', name: 'Orange', icon: '🍊', category: 'Obst' },
    { id: 'mandarin', name: 'Mandarine', icon: '🍊', category: 'Obst' },
    { id: 'grapefruit', name: 'Grapefruit', icon: '🍊', category: 'Obst' },
    { id: 'lemon', name: 'Zitrone', icon: '🍋', category: 'Obst' },
    { id: 'lime', name: 'Limette', icon: '🍋', category: 'Obst' },
    { id: 'strawberry', name: 'Erdbeere', icon: '🍓', category: 'Obst' },
    { id: 'raspberry', name: 'Himbeere', icon: '🍓', category: 'Obst' },
    { id: 'blackberry', name: 'Brombeere', icon: '🫐', category: 'Obst' },
    { id: 'blueberry', name: 'Heidelbeere', icon: '🫐', category: 'Obst' },
    { id: 'grape', name: 'Traube', icon: '🍇', category: 'Obst' },
    { id: 'raisin', name: 'Rosine', icon: '🍇', category: 'Obst' },
    { id: 'mango', name: 'Mango', icon: '🥭', category: 'Obst' },
    { id: 'pineapple', name: 'Ananas', icon: '🍍', category: 'Obst' },
    { id: 'coconut', name: 'Kokosnuss', icon: '🥥', category: 'Obst' },
    { id: 'watermelon', name: 'Wassermelone', icon: '🍉', category: 'Obst' },
    { id: 'honeydew', name: 'Honigmelone', icon: '🍈', category: 'Obst' },
    { id: 'peach', name: 'Pfirsich', icon: '🍑', category: 'Obst' },
    { id: 'apricot', name: 'Aprikose', icon: '🍑', category: 'Obst' },
    { id: 'plum', name: 'Pflaume', icon: '🍑', category: 'Obst' },
    { id: 'cherry', name: 'Kirsche', icon: '🍒', category: 'Obst' },
    { id: 'kiwi', name: 'Kiwi', icon: '🥝', category: 'Obst' },
    { id: 'pear', name: 'Birne', icon: '🍐', category: 'Obst' },
    { id: 'fig', name: 'Feige', icon: '🟤', category: 'Obst' },
    { id: 'date', name: 'Dattel', icon: '🟤', category: 'Obst' },
    { id: 'pomegranate', name: 'Granatapfel', icon: '🔴', category: 'Obst' },
    { id: 'passion_fruit', name: 'Maracuja', icon: '🟤', category: 'Obst' },
  ],

  // Milchprodukte
  dairy: [
    { id: 'milk', name: 'Milch', icon: '🥛', category: 'Milchprodukt' },
    { id: 'whole_milk', name: 'Vollmilch', icon: '🥛', category: 'Milchprodukt' },
    { id: 'buttermilk', name: 'Buttermilch', icon: '🥛', category: 'Milchprodukt' },
    { id: 'cheese', name: 'Käse', icon: '🧀', category: 'Milchprodukt' },
    { id: 'butter', name: 'Butter', icon: '🧈', category: 'Milchprodukt' },
    { id: 'cream', name: 'Sahne', icon: '🥛', category: 'Milchprodukt' },
    { id: 'whipped_cream', name: 'Schlagsahne', icon: '🥛', category: 'Milchprodukt' },
    { id: 'creme_fraiche', name: 'Crème fraîche', icon: '🥛', category: 'Milchprodukt' },
    { id: 'yogurt', name: 'Joghurt', icon: '🥛', category: 'Milchprodukt' },
    { id: 'greek_yogurt', name: 'Griechischer Joghurt', icon: '🥛', category: 'Milchprodukt' },
    { id: 'quark', name: 'Quark', icon: '🥛', category: 'Milchprodukt' },
    { id: 'sour_cream', name: 'Saure Sahne', icon: '🥛', category: 'Milchprodukt' },
    { id: 'schmand', name: 'Schmand', icon: '🥛', category: 'Milchprodukt' },
    { id: 'mascarpone', name: 'Mascarpone', icon: '🧀', category: 'Milchprodukt' },
    { id: 'ricotta', name: 'Ricotta', icon: '🧀', category: 'Milchprodukt' },
    { id: 'cream_cheese', name: 'Frischkäse', icon: '🧀', category: 'Milchprodukt' },
    { id: 'mozzarella', name: 'Mozzarella', icon: '🧀', category: 'Milchprodukt' },
    { id: 'parmesan', name: 'Parmesan', icon: '🧀', category: 'Milchprodukt' },
    { id: 'cheddar', name: 'Cheddar', icon: '🧀', category: 'Milchprodukt' },
    { id: 'gouda', name: 'Gouda', icon: '🧀', category: 'Milchprodukt' },
    { id: 'emmental', name: 'Emmentaler', icon: '🧀', category: 'Milchprodukt' },
    { id: 'feta', name: 'Feta', icon: '🧀', category: 'Milchprodukt' },
    { id: 'brie', name: 'Brie', icon: '🧀', category: 'Milchprodukt' },
    { id: 'camembert', name: 'Camembert', icon: '🧀', category: 'Milchprodukt' },
    { id: 'gorgonzola', name: 'Gorgonzola', icon: '🧀', category: 'Milchprodukt' },
    { id: 'halloumi', name: 'Halloumi', icon: '🧀', category: 'Milchprodukt' },
    { id: 'almond_milk', name: 'Mandelmilch', icon: '🥛', category: 'Pflanzenmilch' },
    { id: 'oat_milk', name: 'Hafermilch', icon: '🥛', category: 'Pflanzenmilch' },
    { id: 'soy_milk', name: 'Sojamilch', icon: '🥛', category: 'Pflanzenmilch' },
    { id: 'coconut_milk', name: 'Kokosmilch', icon: '🥥', category: 'Pflanzenmilch' },
  ],

  // Getreide & Kohlenhydrate
  grains: [
    { id: 'flour', name: 'Mehl', icon: '🌾', category: 'Getreide' },
    { id: 'wheat_flour', name: 'Weizenmehl', icon: '🌾', category: 'Getreide' },
    { id: 'whole_wheat', name: 'Vollkornmehl', icon: '🌾', category: 'Getreide' },
    { id: 'rye_flour', name: 'Roggenmehl', icon: '🌾', category: 'Getreide' },
    { id: 'rice', name: 'Reis', icon: '🍚', category: 'Getreide' },
    { id: 'basmati', name: 'Basmatireis', icon: '🍚', category: 'Getreide' },
    { id: 'risotto_rice', name: 'Risottoreis', icon: '🍚', category: 'Getreide' },
    { id: 'pasta', name: 'Pasta', icon: '🍝', category: 'Getreide' },
    { id: 'spaghetti', name: 'Spaghetti', icon: '🍝', category: 'Getreide' },
    { id: 'penne', name: 'Penne', icon: '🍝', category: 'Getreide' },
    { id: 'fusilli', name: 'Fusilli', icon: '🍝', category: 'Getreide' },
    { id: 'tagliatelle', name: 'Tagliatelle', icon: '🍝', category: 'Getreide' },
    { id: 'lasagna', name: 'Lasagneplatten', icon: '🍝', category: 'Getreide' },
    { id: 'bread', name: 'Brot', icon: '🍞', category: 'Getreide' },
    { id: 'toast', name: 'Toastbrot', icon: '🍞', category: 'Getreide' },
    { id: 'baguette', name: 'Baguette', icon: '🥖', category: 'Getreide' },
    { id: 'breadcrumbs', name: 'Paniermehl', icon: '🍞', category: 'Getreide' },
    { id: 'oats', name: 'Haferflocken', icon: '🥣', category: 'Getreide' },
    { id: 'muesli', name: 'Müsli', icon: '🥣', category: 'Getreide' },
    { id: 'quinoa', name: 'Quinoa', icon: '🌾', category: 'Getreide' },
    { id: 'couscous', name: 'Couscous', icon: '🌾', category: 'Getreide' },
    { id: 'bulgur', name: 'Bulgur', icon: '🌾', category: 'Getreide' },
    { id: 'barley', name: 'Gerste', icon: '🌾', category: 'Getreide' },
    { id: 'polenta', name: 'Polenta', icon: '🌾', category: 'Getreide' },
    { id: 'noodles', name: 'Nudeln', icon: '🍜', category: 'Getreide' },
    { id: 'rice_noodles', name: 'Reisnudeln', icon: '🍜', category: 'Getreide' },
    { id: 'tortilla', name: 'Tortilla', icon: '🌮', category: 'Getreide' },
    { id: 'wrap', name: 'Wrap', icon: '🌮', category: 'Getreide' },
    { id: 'pita', name: 'Pitabrot', icon: '🥙', category: 'Getreide' },
  ],

  // Gewürze & Kräuter (umfassend)
  spices: [
    // Grundgewürze
    { id: 'salt', name: 'Salz', icon: '🧂', category: 'Gewürz' },
    { id: 'sea_salt', name: 'Meersalz', icon: '🧂', category: 'Gewürz' },
    { id: 'pepper', name: 'Pfeffer', icon: '⚫', category: 'Gewürz' },
    { id: 'black_pepper', name: 'Schwarzer Pfeffer', icon: '⚫', category: 'Gewürz' },
    { id: 'white_pepper', name: 'Weißer Pfeffer', icon: '⚪', category: 'Gewürz' },
    // Paprika & Chili
    { id: 'paprika', name: 'Paprikapulver', icon: '🔴', category: 'Gewürz' },
    { id: 'sweet_paprika', name: 'Edelsüß Paprika', icon: '🔴', category: 'Gewürz' },
    { id: 'smoked_paprika', name: 'Geräuchertes Paprika', icon: '🔴', category: 'Gewürz' },
    { id: 'chili', name: 'Chili', icon: '🌶️', category: 'Gewürz' },
    { id: 'chili_flakes', name: 'Chiliflocken', icon: '🌶️', category: 'Gewürz' },
    { id: 'cayenne', name: 'Cayennepfeffer', icon: '🌶️', category: 'Gewürz' },
    // Asiatische Gewürze
    { id: 'ginger', name: 'Ingwer', icon: '🫚', category: 'Gewürz' },
    { id: 'turmeric', name: 'Kurkuma', icon: '🟡', category: 'Gewürz' },
    { id: 'curry', name: 'Currypulver', icon: '🟡', category: 'Gewürz' },
    { id: 'garam_masala', name: 'Garam Masala', icon: '🟤', category: 'Gewürz' },
    { id: 'five_spice', name: 'Fünf-Gewürze', icon: '🟤', category: 'Gewürz' },
    { id: 'star_anise', name: 'Sternanis', icon: '⭐', category: 'Gewürz' },
    { id: 'lemongrass', name: 'Zitronengras', icon: '🌿', category: 'Gewürz' },
    // Mediterrane Gewürze
    { id: 'cumin', name: 'Kreuzkümmel', icon: '🟤', category: 'Gewürz' },
    { id: 'coriander_seeds', name: 'Koriandersamen', icon: '🟤', category: 'Gewürz' },
    { id: 'fennel_seeds', name: 'Fenchelsamen', icon: '🟤', category: 'Gewürz' },
    { id: 'caraway', name: 'Kümmel', icon: '🟤', category: 'Gewürz' },
    { id: 'anise', name: 'Anis', icon: '🟤', category: 'Gewürz' },
    { id: 'sumac', name: 'Sumak', icon: '🔴', category: 'Gewürz' },
    { id: 'zaatar', name: 'Za\'atar', icon: '🟤', category: 'Gewürz' },
    // Süße Gewürze
    { id: 'cinnamon', name: 'Zimt', icon: '🟤', category: 'Gewürz' },
    { id: 'vanilla', name: 'Vanille', icon: '🟤', category: 'Gewürz' },
    { id: 'nutmeg', name: 'Muskatnuss', icon: '🟤', category: 'Gewürz' },
    { id: 'cardamom', name: 'Kardamom', icon: '🟢', category: 'Gewürz' },
    { id: 'cloves', name: 'Nelken', icon: '🟤', category: 'Gewürz' },
    { id: 'allspice', name: 'Piment', icon: '🟤', category: 'Gewürz' },
    { id: 'saffron', name: 'Safran', icon: '🟡', category: 'Gewürz' },
    // Knoblauch & Zwiebel
    { id: 'garlic_powder', name: 'Knoblauchpulver', icon: '🧄', category: 'Gewürz' },
    { id: 'onion_powder', name: 'Zwiebelpulver', icon: '🧅', category: 'Gewürz' },
    // Sonstige
    { id: 'mustard_seeds', name: 'Senfkörner', icon: '🟡', category: 'Gewürz' },
    { id: 'juniper', name: 'Wacholderbeeren', icon: '🔵', category: 'Gewürz' },
    { id: 'sesame', name: 'Sesam', icon: '⚪', category: 'Gewürz' },
    { id: 'poppy_seeds', name: 'Mohn', icon: '⚫', category: 'Gewürz' },
    // Frische Kräuter
    { id: 'basil', name: 'Basilikum', icon: '🌿', category: 'Kräuter' },
    { id: 'oregano', name: 'Oregano', icon: '🌿', category: 'Kräuter' },
    { id: 'thyme', name: 'Thymian', icon: '🌿', category: 'Kräuter' },
    { id: 'rosemary', name: 'Rosmarin', icon: '🌿', category: 'Kräuter' },
    { id: 'sage', name: 'Salbei', icon: '🌿', category: 'Kräuter' },
    { id: 'parsley', name: 'Petersilie', icon: '🌿', category: 'Kräuter' },
    { id: 'cilantro', name: 'Koriander', icon: '🌿', category: 'Kräuter' },
    { id: 'dill', name: 'Dill', icon: '🌿', category: 'Kräuter' },
    { id: 'chives', name: 'Schnittlauch', icon: '🌿', category: 'Kräuter' },
    { id: 'mint', name: 'Minze', icon: '🌿', category: 'Kräuter' },
    { id: 'tarragon', name: 'Estragon', icon: '🌿', category: 'Kräuter' },
    { id: 'marjoram', name: 'Majoran', icon: '🌿', category: 'Kräuter' },
    { id: 'bay_leaf', name: 'Lorbeerblatt', icon: '🍃', category: 'Kräuter' },
    { id: 'lovage', name: 'Liebstöckel', icon: '🌿', category: 'Kräuter' },
    { id: 'chervil', name: 'Kerbel', icon: '🌿', category: 'Kräuter' },
    { id: 'sorrel', name: 'Sauerampfer', icon: '🌿', category: 'Kräuter' },
  ],

  // Öle & Fette
  oils: [
    { id: 'olive_oil', name: 'Olivenöl', icon: '🫒', category: 'Öl' },
    { id: 'extra_virgin', name: 'Natives Olivenöl Extra', icon: '🫒', category: 'Öl' },
    { id: 'vegetable_oil', name: 'Pflanzenöl', icon: '🫒', category: 'Öl' },
    { id: 'sunflower_oil', name: 'Sonnenblumenöl', icon: '🌻', category: 'Öl' },
    { id: 'rapeseed_oil', name: 'Rapsöl', icon: '🫒', category: 'Öl' },
    { id: 'coconut_oil', name: 'Kokosöl', icon: '🥥', category: 'Öl' },
    { id: 'sesame_oil', name: 'Sesamöl', icon: '🫒', category: 'Öl' },
    { id: 'peanut_oil', name: 'Erdnussöl', icon: '🥜', category: 'Öl' },
    { id: 'walnut_oil', name: 'Walnussöl', icon: '🥜', category: 'Öl' },
    { id: 'truffle_oil', name: 'Trüffelöl', icon: '🍄', category: 'Öl' },
    { id: 'butter_oil', name: 'Butter', icon: '🧈', category: 'Fett' },
    { id: 'ghee', name: 'Ghee/Butterschmalz', icon: '🧈', category: 'Fett' },
    { id: 'lard', name: 'Schmalz', icon: '🧈', category: 'Fett' },
    { id: 'margarine', name: 'Margarine', icon: '🧈', category: 'Fett' },
  ],

  // Flüssigkeiten & Getränke
  liquids: [
    { id: 'water', name: 'Wasser', icon: '💧', category: 'Flüssigkeit' },
    { id: 'sparkling_water', name: 'Sprudelwasser', icon: '💧', category: 'Flüssigkeit' },
    { id: 'stock', name: 'Brühe', icon: '🍲', category: 'Flüssigkeit' },
    { id: 'chicken_stock', name: 'Hühnerbrühe', icon: '🍲', category: 'Flüssigkeit' },
    { id: 'beef_stock', name: 'Rinderbrühe', icon: '🍲', category: 'Flüssigkeit' },
    { id: 'vegetable_stock', name: 'Gemüsebrühe', icon: '🍲', category: 'Flüssigkeit' },
    { id: 'wine_red', name: 'Rotwein', icon: '🍷', category: 'Alkohol' },
    { id: 'wine_white', name: 'Weißwein', icon: '🍷', category: 'Alkohol' },
    { id: 'beer', name: 'Bier', icon: '🍺', category: 'Alkohol' },
    { id: 'rum', name: 'Rum', icon: '🥃', category: 'Alkohol' },
    { id: 'vodka', name: 'Wodka', icon: '🥃', category: 'Alkohol' },
    { id: 'gin', name: 'Gin', icon: '🥃', category: 'Alkohol' },
    { id: 'whiskey', name: 'Whiskey', icon: '🥃', category: 'Alkohol' },
    { id: 'brandy', name: 'Weinbrand', icon: '🥃', category: 'Alkohol' },
    { id: 'cognac', name: 'Cognac', icon: '🥃', category: 'Alkohol' },
    { id: 'amaretto', name: 'Amaretto', icon: '🥃', category: 'Alkohol' },
    { id: 'triple_sec', name: 'Triple Sec', icon: '🥃', category: 'Alkohol' },
    { id: 'vermouth', name: 'Wermut', icon: '🥃', category: 'Alkohol' },
    { id: 'vinegar', name: 'Essig', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'balsamic', name: 'Balsamico', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'apple_cider_vinegar', name: 'Apfelessig', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'rice_vinegar', name: 'Reisessig', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'soy_sauce', name: 'Sojasauce', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'fish_sauce', name: 'Fischsauce', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'worcestershire', name: 'Worcestersauce', icon: '🍶', category: 'Flüssigkeit' },
    { id: 'lemon_juice', name: 'Zitronensaft', icon: '🍋', category: 'Saft' },
    { id: 'lime_juice', name: 'Limettensaft', icon: '🍋', category: 'Saft' },
    { id: 'orange_juice', name: 'Orangensaft', icon: '🍊', category: 'Saft' },
    { id: 'apple_juice', name: 'Apfelsaft', icon: '🍎', category: 'Saft' },
    { id: 'cranberry_juice', name: 'Cranberrysaft', icon: '🫐', category: 'Saft' },
    { id: 'tomato_juice', name: 'Tomatensaft', icon: '🍅', category: 'Saft' },
    { id: 'grenadine', name: 'Grenadine', icon: '🔴', category: 'Sirup' },
    { id: 'simple_syrup', name: 'Zuckersirup', icon: '🍯', category: 'Sirup' },
    { id: 'tonic', name: 'Tonic Water', icon: '💧', category: 'Mixer' },
    { id: 'ginger_ale', name: 'Ginger Ale', icon: '💧', category: 'Mixer' },
    { id: 'cola', name: 'Cola', icon: '🥤', category: 'Mixer' },
    { id: 'sprite', name: 'Sprite/7Up', icon: '🥤', category: 'Mixer' },
  ],

  // Süßungsmittel
  sweeteners: [
    { id: 'sugar', name: 'Zucker', icon: '🍚', category: 'Süßungsmittel' },
    { id: 'brown_sugar', name: 'Brauner Zucker', icon: '🍚', category: 'Süßungsmittel' },
    { id: 'powdered_sugar', name: 'Puderzucker', icon: '🍚', category: 'Süßungsmittel' },
    { id: 'cane_sugar', name: 'Rohrzucker', icon: '🍚', category: 'Süßungsmittel' },
    { id: 'honey', name: 'Honig', icon: '🍯', category: 'Süßungsmittel' },
    { id: 'maple_syrup', name: 'Ahornsirup', icon: '🍁', category: 'Süßungsmittel' },
    { id: 'agave', name: 'Agavendicksaft', icon: '🌵', category: 'Süßungsmittel' },
    { id: 'stevia', name: 'Stevia', icon: '🌿', category: 'Süßungsmittel' },
    { id: 'molasses', name: 'Melasse', icon: '🟤', category: 'Süßungsmittel' },
    { id: 'coconut_sugar', name: 'Kokosblütenzucker', icon: '🥥', category: 'Süßungsmittel' },
    { id: 'marzipan', name: 'Marzipan', icon: '🍬', category: 'Süßungsmittel' },
  ],

  // Nüsse & Samen
  nuts: [
    { id: 'almonds', name: 'Mandeln', icon: '🥜', category: 'Nuss' },
    { id: 'walnuts', name: 'Walnüsse', icon: '🥜', category: 'Nuss' },
    { id: 'peanuts', name: 'Erdnüsse', icon: '🥜', category: 'Nuss' },
    { id: 'cashews', name: 'Cashewkerne', icon: '🥜', category: 'Nuss' },
    { id: 'pecans', name: 'Pekannüsse', icon: '🥜', category: 'Nuss' },
    { id: 'hazelnuts', name: 'Haselnüsse', icon: '🥜', category: 'Nuss' },
    { id: 'macadamia', name: 'Macadamia', icon: '🥜', category: 'Nuss' },
    { id: 'pistachios', name: 'Pistazien', icon: '🥜', category: 'Nuss' },
    { id: 'pine_nuts', name: 'Pinienkerne', icon: '🥜', category: 'Nuss' },
    { id: 'chestnuts', name: 'Kastanien', icon: '🌰', category: 'Nuss' },
    { id: 'coconut_flakes', name: 'Kokosflocken', icon: '🥥', category: 'Nuss' },
    { id: 'sesame_seeds', name: 'Sesamkörner', icon: '🌰', category: 'Samen' },
    { id: 'chia_seeds', name: 'Chiasamen', icon: '🌰', category: 'Samen' },
    { id: 'flax_seeds', name: 'Leinsamen', icon: '🌰', category: 'Samen' },
    { id: 'sunflower_seeds', name: 'Sonnenblumenkerne', icon: '🌻', category: 'Samen' },
    { id: 'pumpkin_seeds', name: 'Kürbiskerne', icon: '🎃', category: 'Samen' },
    { id: 'hemp_seeds', name: 'Hanfsamen', icon: '🌿', category: 'Samen' },
  ],

  // Backzutaten
  baking: [
    { id: 'baking_powder', name: 'Backpulver', icon: '🧂', category: 'Backen' },
    { id: 'baking_soda', name: 'Natron', icon: '🧂', category: 'Backen' },
    { id: 'yeast', name: 'Hefe', icon: '🍞', category: 'Backen' },
    { id: 'dry_yeast', name: 'Trockenhefe', icon: '🍞', category: 'Backen' },
    { id: 'vanilla_extract', name: 'Vanilleextrakt', icon: '🍦', category: 'Backen' },
    { id: 'vanilla_sugar', name: 'Vanillezucker', icon: '🍦', category: 'Backen' },
    { id: 'cocoa_powder', name: 'Kakaopulver', icon: '🍫', category: 'Backen' },
    { id: 'chocolate', name: 'Schokolade', icon: '🍫', category: 'Backen' },
    { id: 'dark_chocolate', name: 'Zartbitterschokolade', icon: '🍫', category: 'Backen' },
    { id: 'milk_chocolate', name: 'Vollmilchschokolade', icon: '🍫', category: 'Backen' },
    { id: 'white_chocolate', name: 'Weiße Schokolade', icon: '🍫', category: 'Backen' },
    { id: 'chocolate_chips', name: 'Schokotropfen', icon: '🍫', category: 'Backen' },
    { id: 'cornstarch', name: 'Speisestärke', icon: '🌽', category: 'Backen' },
    { id: 'gelatin', name: 'Gelatine', icon: '🍮', category: 'Backen' },
    { id: 'agar', name: 'Agar-Agar', icon: '🍮', category: 'Backen' },
    { id: 'cream_of_tartar', name: 'Weinstein', icon: '🧂', category: 'Backen' },
    { id: 'food_coloring', name: 'Lebensmittelfarbe', icon: '🎨', category: 'Backen' },
    { id: 'almond_flour', name: 'Mandelmehl', icon: '🥜', category: 'Backen' },
    { id: 'coconut_flour', name: 'Kokosmehl', icon: '🥥', category: 'Backen' },
  ],

  // Saucen & Dips
  condiments: [
    { id: 'ketchup', name: 'Ketchup', icon: '🍅', category: 'Sauce' },
    { id: 'mustard', name: 'Senf', icon: '🟡', category: 'Sauce' },
    { id: 'dijon', name: 'Dijonsenf', icon: '🟡', category: 'Sauce' },
    { id: 'mayonnaise', name: 'Mayonnaise', icon: '🥛', category: 'Sauce' },
    { id: 'aioli', name: 'Aioli', icon: '🥛', category: 'Sauce' },
    { id: 'hot_sauce', name: 'Scharfe Sauce', icon: '🌶️', category: 'Sauce' },
    { id: 'bbq_sauce', name: 'BBQ Sauce', icon: '🍖', category: 'Sauce' },
    { id: 'sriracha', name: 'Sriracha', icon: '🌶️', category: 'Sauce' },
    { id: 'tabasco', name: 'Tabasco', icon: '🌶️', category: 'Sauce' },
    { id: 'sambal', name: 'Sambal Oelek', icon: '🌶️', category: 'Sauce' },
    { id: 'tahini', name: 'Tahini', icon: '🥜', category: 'Sauce' },
    { id: 'hummus', name: 'Hummus', icon: '🦴', category: 'Dip' },
    { id: 'pesto', name: 'Pesto', icon: '🌿', category: 'Sauce' },
    { id: 'pesto_rosso', name: 'Pesto Rosso', icon: '🍅', category: 'Sauce' },
    { id: 'tomato_paste', name: 'Tomatenmark', icon: '🍅', category: 'Sauce' },
    { id: 'tomato_sauce', name: 'Tomatensauce', icon: '🍅', category: 'Sauce' },
    { id: 'passata', name: 'Passierte Tomaten', icon: '🍅', category: 'Sauce' },
    { id: 'harissa', name: 'Harissa', icon: '🌶️', category: 'Paste' },
    { id: 'curry_paste', name: 'Currypaste', icon: '🟡', category: 'Paste' },
    { id: 'miso', name: 'Misopaste', icon: '🟤', category: 'Paste' },
    { id: 'oyster_sauce', name: 'Austernsauce', icon: '🪦', category: 'Sauce' },
    { id: 'hoisin', name: 'Hoisin-Sauce', icon: '🟤', category: 'Sauce' },
    { id: 'teriyaki', name: 'Teriyaki-Sauce', icon: '🍶', category: 'Sauce' },
    { id: 'tzatziki', name: 'Tzatziki', icon: '🥛', category: 'Dip' },
    { id: 'guacamole', name: 'Guacamole', icon: '🥑', category: 'Dip' },
    { id: 'salsa', name: 'Salsa', icon: '🍅', category: 'Dip' },
  ],
};

// Units for quantity selection
export const UNITS = [
  { id: 'cl', name: 'cl', type: 'volume', icon: '🥃' },
  { id: 'ml', name: 'ml', type: 'volume', icon: '🥃' },
  { id: 'oz', name: 'oz', type: 'volume', icon: '🥃' },
  { id: 'l', name: 'L', type: 'volume', icon: '🥃' },
  { id: 'g', name: 'g', type: 'weight', icon: '⚖️' },
  { id: 'kg', name: 'kg', type: 'weight', icon: '⚖️' },
  { id: 'pinch', name: 'Prise', type: 'special', icon: '👆' },
  { id: 'pieces', name: 'Stück', type: 'count', icon: '🔢' },
  { id: 'tbsp', name: 'EL', type: 'volume', icon: '🥄' },
  { id: 'tsp', name: 'TL', type: 'volume', icon: '🥄' },
  { id: 'cup', name: 'Cup', type: 'volume', icon: '☕' },
  { id: 'handful', name: 'Handvoll', type: 'special', icon: '🤚' },
];

// Get all ingredients as flat array
export const getAllIngredients = () => {
  return Object.values(INGREDIENTS_DATABASE).flat();
};

// Search ingredients
export const searchIngredients = (query) => {
  if (!query) return getAllIngredients();
  
  const allIngredients = getAllIngredients();
  return allIngredients.filter(ingredient => 
    ingredient.name.toLowerCase().includes(query.toLowerCase()) ||
    ingredient.id.toLowerCase().includes(query.toLowerCase())
  );
};

// Get ingredients by category
export const getIngredientsByCategory = (category) => {
  return INGREDIENTS_DATABASE[category] || [];
};

// Get ingredient by ID
export const getIngredientById = (id) => {
  const allIngredients = getAllIngredients();
  return allIngredients.find(ingredient => ingredient.id === id);
};
